### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by LucianoSegundo** [LucianoSegundo/GCMS-Luciano-Filho#2]
@ramidedantas
- [ ]  Instalar Git localmente
- [ ]  Criar projeto local
- [ ]  Criar repositório local e realizar commits
- [ ]  Subir alterações para o repositório remoto
- [ ] Fazer alterações no repositório da turma

**Comment by ramidedantas** [comment]
@LucianoSegundo, checklist não está correto. Use a sintaxe abaixo:
- [ ] Item 1
- [ ] Item 2
- [ ] Item 3

**Comment by LucianoSegundo** [comment]
Corrigido
